import Sidebar from '../components/Sidebar'
import Feed from "../components/Feed"
import Widgets from '@/components/Widgets'
import Head from 'next/head'


export default function Home({ newsResults , randomUserResults }) {
  return (
    <div>
      <Head>
        <title>Social</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen mx-auto'>
        <Sidebar />
        <Feed />
        <Widgets newsResults={newsResults.articles} randomUserResults={randomUserResults.results} />
      </main>
    </div>
  )
}


//https://saurav.tech/NewsAPI/top-headlines/category/bussiness/us.json


export async function getServerSideProps() {
  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());
  const randomUserResults = await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture"
  ).then((res) => res.json());
  return {
    props: {
      newsResults,
      randomUserResults,
    }
  }
}